server:
  port: 8989
  servlet:
    context-path: /ms
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms?characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 192.168.56.10
    port: 6379
    database: 0

mybatis:
  mapper-locations: classpath:com/yjh/mapper/*.xml
  type-aliases-package: com.yjh.entity


logging:
  level:
    root: info
    com.yjh.dao: debug


